### PR TITLE
feat: ability to present MMT surface syntax in sidekick

### PR DESCRIPTION
**Pull request by ComFreek**
cc @rappatoni who requested this feature.

You can now right-click in the sidekick to present surface syntax:

image

For example, this is useful when you generate theories on-the-fly by means of diagram operators. In the screenshot you can see my pushout theory generated by my `PUSHOUT ... ALONG ...` operator. That theory is only available in-memory!

This needs the latest MMT devel commit.

### CODE REVIEW

**Comment by kohlhase** [comment]
This is great, I had wished for something like this for a long time. And in particular, Jacques Carette has been waiting for this (if MMT does not have this, then I cannot take it seriously; not that I take his opinion in this matter fully seriously)

**Comment by kohlhase** [comment]
BTW, is there any documentation for the plugin, which should be extended by a description of this functionality?

**Comment by ComFreek** [comment]
@kohlhase Yes, I've just revised and updated the docs: https://uniformal.github.io//doc/applications/intellij/index.html

**Comment by rappatoni** [comment]
Aweseome, thanks!

**Pull request merged**
