### PR TITLE
Allow IntelliJ IDEA 2020.1:* in plugin metadata

### PR DESCRIPTION
**Pull request by ComFreek**
@Jazzpirate IntelliJ IDEA 2020.1 is out of early-access preview and people start using it, esp. in some courses by Florian. Could you check whether it works and make a release then? Perhaps just some minor release to keep in sync with MMT major versions.

### CODE REVIEW

**Comment by Jazzpirate** [comment]
thank you :)

**Comment by Jazzpirate** [comment]
Unfortunately, the Plugin API for v2020.1.+ has changed significantly - will take me a while to clean up things. Working on it

**Comment by Jazzpirate** [comment]
pushed and published. Disadvantage: MMT windows (MMT at the bottom, refactoring on the right) might now be present always, regardless of project type :/

**Comment by ComFreek** [comment]
Thanks for the fast fixing!

> pushed and published. Disadvantage: MMT windows (MMT at the bottom, refactoring on the right) might now be present always, regardless of project type :/

Uh, this is a bummer. It this a consequence of the quickfix or the new plugin APIs? I cannot imagine that every installed plugin should display its panes for every project.

**Comment by Jazzpirate** [comment]
> Uh, this is a bummer. It this a consequence of the quickfix or the new plugin APIs?

It's a consequence of previous methods for dynamically adding/removing components being deprecated, a lack of easily findable documentation on how to migrate from components to services properly, and me doing my best to get things to work *quickly* :D

I'm sure there's a better way - if you have time and care to look at things, I'd very much appreciate it. For now this is the best I can do on short notice until I have mental space to dig deeper ;)

**Pull request merged**
